### ISSUE TITLE
TTorrentReader: Get all Announce List items and adapt them to a special list format.

### ISSUE THREAD

**Issue by laoqiuqiu** [bnzbnz/qBit4Delphi#2]
chanage uTorrentReader.pas
```
  // AnnounceList
  var AnnounceList := Be.ListData.FindElement('announce-list') as TBencoded;
  if assigned(AnnounceList) then
    begin
      var SubList := AnnounceList.ListData[0].Data;
      for var i := 0 to SubList.ListData.Count - 1 do
        FData.AnnounceList.Add(UTF8ToString((SubList.ListData[i].Data).StringData));
    end;
```

to

```
  // AnnounceList
  var AnnounceList := Be.ListData.FindElement('announce-list') as TBencoded;
  if assigned(AnnounceList) then
  begin
    if (AnnounceList.ListData[0].Data.Format = befList) then
    begin
      for var i := 0 to AnnounceList.ListData.Count - 1 do
        FData.AnnounceList.Add(UTF8ToString((AnnounceList.ListData[i].Data.ListData[0].Data).StringData));
    end
    else
      for var i := 0 to AnnounceList.ListData.Count - 1 do
        FData.AnnounceList.Add(UTF8ToString((AnnounceList.ListData[i].Data).StringData))
  end;
```

**Comment by bnzbnz** [comment]
OK, Could you send me the torrent file with this issue, I don't really get the user case : qBit4Delphi@ea4d.com

**Comment by laoqiuqiu** [comment]
### Multitracker Metadata Extension

    http://bittorrent.org/beps/bep_0012.html

**Comment by bnzbnz** [comment]
Fix committed to main branch. Please Check

**Comment by laoqiuqiu** [comment]
I think we should use a recursive function to iterate over each element and add it to the Announce List.

**Comment by bnzbnz** [comment]
Looking at qBit4Delphi source, you can see that the Ftrackersis a dictionary of TStringList: (uqBitAPITypes.pas, line 481)
TierID (Order in the announce list) to a List of String. So it is not recursive. I was able to create few multi announce torrent to with multi announce tier groups using qBittorrent (leave a blank line to create tier groups)
Still I am adding the TierId  to the AnnounceList list as Object property...
Please test on your side if possible.
Thank you.

**Comment by bnzbnz** [comment]
It could also be a TCollection.... What do you think ?

**Comment by laoqiuqiu** [comment]
### Supporting for in loop in TObjectList descendants
    https://www.remkoweijnen.nl/blog/2008/03/02/supporting-for-in-loop-in-tobjectlist-descendants/

**Comment by bnzbnz** [comment]
I have replaced AnnounceList by a dictionary : TDictionary<Integer, TStringList> for Tier/URLList.
You get native enumeration
